# Generated by Django 4.1.7 on 2023-02-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='products',
        ),
        migrations.CreateModel(
            name='CompanyProdacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.company')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.products')),
            ],
        ),
    ]
