# Generated by Django 4.1.7 on 2023-02-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_remove_company_products_companyprodacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyProdacts',
            new_name='CompanyProducts',
        ),
    ]
